
spring:

  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    
logging:
  level:
    root: ERROR
    '[br.com.alura.challenge.finance.backend]': ERROR 